(window.AMP = window.AMP || []).push(function(AMP) {var process={env:{NODE_ENV:"production"}};var g={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};g.global=g.getGlobal(this);g.initSymbol=function(){g.global.Symbol||(g.global.Symbol=g.Symbol);g.initSymbol=function(){}};g.symbolCounter_=0;g.Symbol=function(a){return"jscomp_symbol_"+a+g.symbolCounter_++};g.initSymbolIterator=function(){g.initSymbol();g.global.Symbol.iterator||(g.global.Symbol.iterator=g.global.Symbol("iterator"));g.initSymbolIterator=function(){}};
g.makeIterator=function(a){g.initSymbolIterator();if(a[g.global.Symbol.iterator])return a[g.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};g.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};g.arrayFromIterable=function(a){return a instanceof Array?a:g.arrayFromIterator(g.makeIterator(a))};
g.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};g.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(g.global.Object.defineProperties){var e=g.global.Object.getOwnPropertyDescriptor(b,d);void 0!==e&&g.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};var h={};function k(a){return Error(a+"\u200b\u200b\u200b")}h.ASSERT_SENTINEL="\u200b\u200b\u200b";
h.assert=function(a,b,c){var d=void 0;if(!a){var e=(b||"Assertion failed").split("%s"),f=e.shift(),n=f,B=[];""!=f&&B.push(f);for(f=2;f<arguments.length;f++){var y=arguments[f];y&&y.tagName&&(d=y);var aa=e.shift();B.push(y);var ba=aa.trim();""!=ba&&B.push(ba);y=y instanceof Element?y.tagName.toLowerCase()+(y.id?"#"+y.id:""):y;n+=y+aa}e=k(n);e.fromAssert=!0;e.associatedElement=d;e.messageArray=B;throw e;}return a};
h.assertEnumValue=function(a,b,c){for(var d in a)if(a[d]==b)return a[d];throw Error("Unknown "+(c||"enum")+' value: "'+b+'"');};h.userError=k;h.isAssertErrorMessage=function(a){return 0<=a.indexOf("\u200b\u200b\u200b")};var ca={dashToCamelCase:function(a){return a.replace(/-([a-z])/g,function(a,c){return c.toUpperCase()})},endsWith:function(a,b){return b.length>a.length?!1:a.lastIndexOf(b)==a.length-b.length},expandTemplate:function(a,b,c){c=c||1;for(var d={matches:void 0},e=0;e<c&&(d.matches=0,a=a.replace(/\${([^}]*)}/g,function(a){return function(c,d){a.matches++;return b(d)}}(d)),d.matches);d={matches:d.matches},e++);return a}};var l={},m=document.createElement("a"),da=Object.create(null);function p(a){var b=da[a];if(b)return b;m.href=a;b={href:m.href,protocol:m.protocol,host:m.host,hostname:m.hostname,port:"0"==m.port?"":m.port,pathname:m.pathname,search:m.search,hash:m.hash};b.origin=m.origin&&"null"!=m.origin?m.origin:q(b);h.assert(b.origin,"Origin must exist");da[a]=window.AMP_TEST&&Object.freeze?Object.freeze(b):b;return b}
function ea(a,b,c){a=p(a);b=encodeURIComponent(b)+"="+encodeURIComponent(c);return a.origin+a.pathname+(a.search?a.search+"&"+b:"?"+b)+a.hash}function q(a){"string"==typeof a&&(a=p(a));return"data:"!=a.protocol&&a.host?a.protocol+"//"+a.host:a.href}function fa(a){"string"==typeof a&&(a=p(a));var b=a.pathname.split("/")[1];return"https://cdn.ampproject.org"==a.origin||0==a.origin.indexOf("../localhost:/")&&("c"==b||"v"==b)}
function ga(a){"string"==typeof a&&(a=p(a));if(!fa(a))return a.href;var b=a.pathname.split("/"),c=b[1];h.assert("c"==c||"v"==c,"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"../https@/"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);h.assert(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);return d+b.join("default.htm")+(a.search||"")+(a.hash||"")}
function ha(a,b){"string"==typeof b&&(b=p(b));a=a.replace(/\\/g,"default.htm");var c=p(a);if(0==a.toLowerCase().indexOf(c.protocol))return c.href;if(0==a.indexOf("//"))return b.protocol+a;if(0==a.indexOf("/"))return b.origin+a;c=b.pathname.split("/");return b.origin+(1<c.length?c.slice(0,c.length-1).join("default.htm"):"")+"/"+a}l.parseUrl=p;l.addParamToUrl=ea;l.addParamsToUrl=function(a,b){return Object.keys(b).reduce(function(a,d){return ea(a,d,b[d])},a)};
l.assertHttpsUrl=function(a,b){var c=p(a);h.assert("https:"==c.protocol||/^(\/\/)/.test(a)||"localhost"==c.hostname||ca.endsWith(c.hostname,".localhost"),'%s source must start with "../https@/" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,a);return a};l.assertAbsoluteHttpOrHttpsUrl=function(a){h.assert(/^(http\:|https\:)/i.test(a),'URL must start with "http://" or "../https@/". Invalid value: %s',a);return p(a).href};
l.parseQueryString=function(a){var b=Object.create(null);if(!a)return b;if(0==a.indexOf("?")||0==a.indexOf("#"))a=a.substr(1);a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c],e=d.indexOf("="),f=void 0,n=void 0;-1!=e?(f=decodeURIComponent(d.substring(0,e)).trim(),n=decodeURIComponent(d.substring(e+1)).trim()):(f=decodeURIComponent(d).trim(),n="");f&&(b[f]=n)}return b};l.getOrigin=q;l.removeFragment=function(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};l.isProxyOrigin=fa;
l.getSourceUrl=ga;l.getSourceOrigin=function(a){return q(ga(a))};l.resolveRelativeUrl=function(a,b){"string"==typeof b&&(b=p(b));return"function"==typeof URL?(new URL(a,b.href)).toString():ha(a,b)};l.resolveRelativeUrlFallback_=ha;var r={};function t(a){var b=a.services;b||(b=a.services={});return b}r.getService=function(a,b,c){var d=t(a),e=d[b];e||(e=d[b]={obj:null,promise:null,resolve:null});e.obj||(h.assert(c,"Factory not given and service missing %s",b),e.obj=c(a),e.promise||(e.promise=Promise.resolve(e.obj)),e.resolve&&e.resolve(e.obj));return e.obj};r.getServicePromise=function(a,b){var c=t(a),d=c[b];if(d)return d.promise;var e=void 0,d=new Promise(function(a){e=a});c[b]={obj:null,promise:d,resolve:e};return d};
r.getServicePromiseOrNull=function(a,b){var c=t(a);return c[b]?c[b].promise:null};r.resetServiceForTesting=function(a,b){a.services&&(a.services[b]=null)};var u={},v=null;
u.getMode=function(){if(v)return v;var a;if(window.context&&window.context.mode)a=window.context.mode;else{a=("localhost"==location.hostname||location.ancestorOrigins&&location.ancestorOrigins[0]&&0==location.ancestorOrigins[0].indexOf("../localhost:/"))&&!!document.querySelector('script[src*="dist/default.htm"],script[src*="base/default.htm"]');var b=l.parseQueryString(location.originalHash||location.hash).development;a={localDev:a,development:"1"==b||window.AMP_DEV_MODE,minified:"production"==process.env.NODE_ENV,test:window.AMP_TEST}}return v=
a};u.setModeForTesting=function(a){v=a};var w={},ia=(new Date).getTime();function x(a){this.win=a.AMP_TEST?a.parent:a;this.isEnabled_=this.shouldBeEnabled_()}x.prototype.shouldBeEnabled_=function(){if(!this.win.console||!this.win.console.log)return!1;if(this.win.ENABLE_LOG)return!0;var a=this.win.location.hash.match(/log=(\d)/),a=a&&a[1];return u.getMode().localDev&&"0"!=a||this.win.location.hash&&"1"==a?!0:!1};
x.prototype.msg_=function(a,b,c){if(this.isEnabled_){var d=this.win.console.log;"ERROR"==b?d=this.win.console.error||d:"INFO"==b?d=this.win.console.info||d:"WARN"==b&&(d=this.win.console.warn||d);c.unshift((new Date).getTime()-ia,"["+a+"]");d.apply(this.win.console,c)}};x.prototype.fine=function(a,b){this.isEnabled_&&this.msg_(a,"FINE",Array.prototype.slice.call(arguments,1))};x.prototype.info=function(a,b){this.isEnabled_&&this.msg_(a,"INFO",Array.prototype.slice.call(arguments,1))};
x.prototype.warn=function(a,b){this.isEnabled_&&this.msg_(a,"WARN",Array.prototype.slice.call(arguments,1))};x.prototype.error=function(a,b){this.isEnabled_&&this.msg_(a,"ERROR",Array.prototype.slice.call(arguments,1))};var ja=new x(window);w.Log=x;w.log=ja;var z={},ka=Object.create(null),la="Webkit webkit Moz moz ms O o".split(" ");function ma(a){return a.charAt(0).toUpperCase()+a.slice(1)}function A(a,b,c){var d=ka[b];if(!d||c){d=b;if(void 0===a[b]){var e=ma(b);a:{for(var f=0;f<la.length;f++){var n=la[f]+e;if(void 0!==a[n]){e=n;break a}}e=""}void 0!==a[e]&&(d=e)}c||(ka[b]=d)}return d}function na(a,b,c,d,e){(b=A(a.style,b,e))&&(a.style[b]=d?c+d:c)}function C(a){return a+"px"}z.camelCaseToTitleCase=ma;z.getVendorJsPropertyName=A;z.setStyle=na;
z.getStyle=function(a,b,c){return(b=A(a.style,b,c))?a.style[b]:void 0};z.setStyles=function(a,b){for(var c in b)na(a,c,b[c])};z.toggle=function(a,b){void 0===b&&(b="none"==a.style.display);a.style.display=b?"":"none"};z.px=C;z.translateX=function(a){return"string"==typeof a?"translateX("+a+")":"translateX("+C(a)+")"};z.translate=function(a,b){"number"==typeof a&&(a=C(a));if(void 0===b)return"translate("+a+")";"number"==typeof b&&(b=C(b));return"translate("+a+","+b+")"};
z.scale=function(a){return"scale("+a+")"};var oa={vsyncFor:function(a){return r.getService(a,"vsync")}};function D(){this.handlers_=[]}D.prototype.add=function(a){var b=this;this.handlers_.push(a);return function(){b.remove(a)}};D.prototype.remove=function(a){for(var b=0;b<this.handlers_.length;b++)if(a==this.handlers_[b]){this.handlers_.splice(b,1);break}};D.prototype.fire=function(a){this.handlers_.forEach(function(b){b(a)})};D.prototype.getHandlerCount=function(){return this.handlers_.length};var E={};function F(a){this.win=a;this.resolved_=Promise.resolve();this.taskCount_=0;this.canceled_={};this.startTime_=this.now()}F.prototype.now=function(){return Number(new Date)};F.prototype.timeSinceStart=function(){return this.now()-this.startTime_};F.prototype.delay=function(a,b){if(!b){var c=this,d="p"+this.taskCount_++;this.resolved_.then(function(){c.canceled_[d]?delete c.canceled_[d]:a()});return d}return this.win.setTimeout(a,b)};
F.prototype.cancel=function(a){"string"==typeof a?this.canceled_[a]=!0:this.win.clearTimeout(a)};F.prototype.promise=function(a,b){var c=this,d=null;return(new Promise(function(e,f){d=c.delay(function(){d=-1;e(b)},a);-1==d&&f(Error("Failed to schedule timer."))})).catch(function(a){-1!=d&&c.cancel(d);throw a;})};
F.prototype.timeoutPromise=function(a,b,c){var d=this,e=null,f=(new Promise(function(b,f){e=d.delay(function(){e=-1;f(h.userError(c||"timeout"))},a);-1==e&&f(Error("Failed to schedule timer."))})).catch(function(a){-1!=e&&d.cancel(e);throw a;});return b?Promise.race([f,b]):f};var pa=new F(window);E.Timer=F;E.timer=pa;var G={},H={NODISPLAY:"nodisplay",FIXED:"fixed",FIXED_HEIGHT:"fixed-height",RESPONSIVE:"responsive",CONTAINER:"container",FILL:"fill"},I={"AMP-PIXEL":{width:"1px",height:"1px"},"AMP-ANALYTICS":{width:"1px",height:"1px"},"AMP-AUDIO":null},qa={"AMP-ANIM":!0,"AMP-BRIGHTCOVE":!0,"AMP-EMBED":!0,"AMP-IFRAME":!0,"AMP-IMG":!0,"AMP-INSTAGRAM":!0,"AMP-LIST":!0,"AMP-PINTEREST":!0,"AMP-VIDEO":!0};
function ra(a){h.assert(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax)$/.test(a),"Invalid length value: %s",a);return a}G.Layout=H;G.naturalDimensions_=I;G.LOADING_ELEMENTS_=qa;G.parseLayout=function(a){for(var b in H)if(H[b]==a)return H[b]};G.getLayoutClass=function(a){return"-amp-layout-"+a};G.isLayoutSizeDefined=function(a){return a==H.FIXED||a==H.FIXED_HEIGHT||a==H.RESPONSIVE||a==H.FILL};G.isInternalElement=function(a){return(a="string"==typeof a?a:a.tagName)&&0==a.toLowerCase().indexOf("i-")};
G.parseLength=function(a){return"number"==typeof a?a+"px":a&&/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax)?$/.test(a)?/^\d+(\.\d+)?$/.test(a)?a+"px":a:void 0};G.assertLength=ra;G.assertLengthOrPercent=function(a){h.assert(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|%)$/.test(a),"Invalid length or percent value: %s",a);return a};G.getLengthUnits=function(a){ra(a);return h.assert(a.match(/[a-z]+/i),"Failed to read units from %s",a)[0]};G.getLengthNumeral=function(a){return parseFloat(a)};
G.hasNaturalDimensions=function(a){a=a.toUpperCase();return void 0!==I[a]};G.getNaturalDimensions=function(a){a=a.toUpperCase();h.assert(void 0!==I[a]);if(!I[a]){var b=a.replace(/^AMP\-/,""),b=document.createElement(b);b.controls=!0;b.style.position="absolute";b.style.visibility="hidden";document.body.appendChild(b);I[a]={width:(b.offsetWidth||1)+"px",height:(b.offsetHeight||1)+"px"};document.body.removeChild(b)}return I[a]};G.isLoadingAllowed=function(a){return qa[a.toUpperCase()]||!1};var J={};function sa(){}var ta=Math.round(-16.67/Math.log(.95));function K(a,b,c,d,e,f){var n=this;this.vsync_=f||oa.vsyncFor(window);this.callback_=e;this.lastX_=a;this.lastY_=b;this.maxVelocityX_=c;this.maxVelocityY_=d;this.velocityY_=this.velocityX_=0;this.lastTime_=this.startTime_=E.timer.now();this.promise_=new Promise(function(a,b){n.resolve_=a;n.reject_=b})}
K.prototype.start_=function(){this.continuing_=!0;.02>=Math.abs(this.maxVelocityX_)&&.02>=Math.abs(this.maxVelocityY_)?(this.fireMove_(),this.completeContinue_(!0)):this.runContinuing_();return this};K.prototype.halt=function(){this.continuing_&&this.completeContinue_(!1)};K.prototype.then=function(a,b){return a||b?this.promise_.then(a,b):this.promise_};K.prototype.thenAlways=function(a){a=a||sa;return this.then(a,a)};
K.prototype.runContinuing_=function(){this.velocityX_=this.maxVelocityX_;this.velocityY_=this.maxVelocityY_;var a=this.stepContinue_.bind(this),b=this.completeContinue_.bind(this,!0);return this.vsync_.runAnimMutateSeries(a,5E3).then(b,b)};
K.prototype.stepContinue_=function(a,b){if(!this.continuing_)return!1;this.lastTime_=E.timer.now();this.lastX_+=b*this.velocityX_;this.lastY_+=b*this.velocityY_;if(!this.fireMove_())return!1;var c=Math.exp(-a/ta);this.velocityX_=this.maxVelocityX_*c;this.velocityY_=this.maxVelocityY_*c;return.02<Math.abs(this.velocityX_)||.02<Math.abs(this.velocityY_)};K.prototype.completeContinue_=function(a){this.continuing_&&(this.continuing_=!1,this.lastTime_=E.timer.now(),this.fireMove_(),a?this.resolve_():this.reject_())};
K.prototype.fireMove_=function(){return this.callback_(this.lastX_,this.lastY_)};J.calcVelocity=function(a,b,c){1>b&&(b=1);var d=.5+Math.min(b/33.34,.5);return a/b*d+c*(1-d)};J.continueMotion=function(a,b,c,d,e,f){return(new K(a,b,c,d,e,f)).start_()};var L={};function M(a,b,c,d){a=new N(0,0,a,b,c,d,1,1);return a.solveYValueFromXValue.bind(a)}function N(a,b,c,d,e,f,n,B){this.x0=a;this.y0=b;this.x1=c;this.y1=d;this.x2=e;this.y2=f;this.x3=n;this.y3=B}N.prototype.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
N.prototype.solvePositionFromXValue=function(a){var b=(a-this.x0)/(this.x3-this.x0);if(0>=b)return 0;if(1<=b)return 1;for(var c=0,d=1,e=0;8>e;e++){var f=this.getPointX(b),n=(this.getPointX(b+1E-6)-f)/1E-6;if(1E-6>Math.abs(f-a))return b;if(1E-6>Math.abs(n))break;else f<a?c=b:d=b,b-=(f-a)/n}for(e=0;1E-6<Math.abs(value-a)&&8>e;e++)value<a?(c=b,b=(b+d)/2):(d=b,b=(b+c)/2),value=this.getPointX(b);return b};
N.prototype.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};N.prototype.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};
N.prototype.lerp=function(a,b,c){return a+c*(b-a)};var O={LINEAR:function(a){return a},EASE:M(.25,.1,.25,1),EASE_IN:M(.42,0,1,1),EASE_OUT:M(0,0,.58,1),EASE_IN_OUT:M(.42,0,.58,1)},ua={linear:O.LINEAR,ease:O.EASE,"ease-in":O.EASE_IN,"ease-out":O.EASE_OUT,"ease-in-out":O.EASE_IN_OUT};L.bezierCurve=M;L.Curves=O;L.getCurve=function(a){return a?"string"==typeof a?ua[a]:a:null};function va(){}function P(a){this.vsync_=a||oa.vsyncFor(window);this.curve_=null;this.segments_=[]}P.animate=function(a,b,c){return(new P).setCurve(c).add(0,a,1).start(b)};P.prototype.setCurve=function(a){this.curve_=L.getCurve(a);return this};P.prototype.add=function(a,b,c,d){this.segments_.push({delay:a,func:b,duration:c,curve:L.getCurve(d)});return this};P.prototype.start=function(a){a=new Q(this.vsync_,this.segments_,this.curve_,a);a.start_();return a};
function Q(a,b,c,d){var e=this;this.vsync_=a;this.segments_=[];for(a=0;a<b.length;a++){var f=b[a];this.segments_.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||c,started:!1,completed:!1})}this.duration_=d;this.normTime_=this.normLinearTime_=this.startTime_=0;this.running_=!1;this.state_={};this.promise_=new Promise(function(a,b){e.resolve_=a;e.reject_=b});this.task_=this.vsync_.createAnimTask({mutate:this.stepMutate_.bind(this)})}
Q.prototype.then=function(a,b){return a||b?this.promise_.then(a,b):this.promise_};Q.prototype.thenAlways=function(a){a=a||va;return this.then(a,a)};Q.prototype.halt=function(a){this.complete_(!1,a||0)};Q.prototype.start_=function(){this.startTime_=E.timer.now();this.running_=!0;this.vsync_.canAnimate()?this.task_(this.state_):(w.log.warn("Animation","cannot animate"),this.complete_(!1,0))};
Q.prototype.complete_=function(a,b){if(this.running_){this.running_=!1;if(0!=b){1<this.segments_.length&&this.segments_.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<b)for(var c=0;c<this.segments_.length;c++)this.segments_[c].func(1,!0);else for(c=this.segments_.length-1;0<=c;c--)this.segments_[c].func(0,!1)}catch(d){w.log.error("Animation","completion failed: "+d,d),a=!1}}a?this.resolve_():this.reject_()}};
Q.prototype.stepMutate_=function(){if(this.running_){for(var a=E.timer.now(),a=Math.min((a-this.startTime_)/this.duration_,1),b=0;b<this.segments_.length;b++){var c=this.segments_[b];!c.started&&a>=c.delay&&(c.started=!0)}for(b=0;b<this.segments_.length;b++)c=this.segments_[b],c.started&&!c.completed&&this.mutateSegment_(c,a);1==a?this.complete_(!0,0):this.vsync_.canAnimate()?this.task_(this.state_):(w.log.warn("Animation","cancel animation"),this.complete_(!1,0))}};
Q.prototype.mutateSegment_=function(a,b){var c=void 0,d=void 0;if(0<a.duration){if(d=c=Math.min((b-a.delay)/a.duration,1),a.curve&&1!=d)try{d=a.curve(c)}catch(e){w.log.error("Animation","step curve failed: "+e,e);this.complete_(!1,0);return}}else d=c=1;1==c&&(a.completed=!0);try{a.func(d,a.completed)}catch(e){w.log.error("Animation","step mutate failed: "+e,e),this.complete_(!1,0)}};var R={};function wa(a,b){return function(c){return a+(b-a)*c}}R.NOOP=function(){return null};R.all=function(a){return function(b,c){for(var d=0;d<a.length;d++)(0,a[d])(b,c)}};R.withCurve=function(a,b){b=L.getCurve(b);return function(c,d){return a(d?1:b(c),d)}};R.setStyles=function(a,b){return function(c,d){for(var e in b)z.setStyle(a,e,b[e](c,d))}};R.numeric=wa;R.spring=function(a,b,c,d){return b==c?function(c){return wa(a,b)(c)}:function(e){return e<d?a+e/d*(c-a):c+(e-d)/(1-d)*(b-c)}};
R.px=function(a){return function(b){return a(b)+"px"}};R.translateX=function(a){return function(b){b=a(b);return"string"==typeof b?"translateX("+b+")":"translateX("+b+"px)"}};R.translate=function(a,b){return function(c){var d=a(c);"number"==typeof d&&(d=z.px(d));if(!b)return"translate("+d+")";c=b(c);"number"==typeof c&&(c=z.px(c));return"translate("+d+","+c+")"}};R.scale=function(a){return function(b){return"scale("+a(b)+")"}};function S(a,b){this.handler_=a;this.defaultDelay_=b||0;this.scheduled_=-1;this.nextTime_=0;this.running_=!1}S.prototype.isPending=function(){return-1!=this.scheduled_};
S.prototype.schedule=function(a){a=a||this.defaultDelay_;this.running_&&10>a&&(a=10);var b=E.timer.now()+a;if(-1==this.scheduled_||-10>b-this.nextTime_){var c=this;-1!=this.scheduled_&&E.timer.cancel(this.scheduled_);this.nextTime_=b;this.scheduled_=E.timer.delay(function(){c.scheduled_=-1;c.nextTime_=0;c.running_=!0;c.handler_();c.running_=!1},a);return!0}return!1};S.prototype.cancel=function(){-1!=this.scheduled_&&(E.timer.cancel(this.scheduled_),this.scheduled_=-1)};function xa(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function T(a){this.element_=a;this.recognizers_=[];this.tracking_=[];this.ready_=[];this.pending_=[];this.eventing_=null;this.wasEventing_=!1;this.pass_=new S(this.doPass_.bind(this));this.pointerDownObservable_=new D;this.overservers_=Object.create(null);this.boundOnTouchStart_=this.onTouchStart_.bind(this);this.boundOnTouchEnd_=this.onTouchEnd_.bind(this);this.boundOnTouchMove_=this.onTouchMove_.bind(this);this.boundOnTouchCancel_=this.onTouchCancel_.bind(this);this.element_.addEventListener("touchstart",
this.boundOnTouchStart_);this.element_.addEventListener("touchend",this.boundOnTouchEnd_);this.element_.addEventListener("touchmove",this.boundOnTouchMove_);this.element_.addEventListener("touchcancel",this.boundOnTouchCancel_)}T.get=function(a){var b=a.__AMP_Gestures;b||(b=new T(a),a.__AMP_Gestures=b);return b};
T.prototype.cleanup=function(){this.element_.removeEventListener("touchstart",this.boundOnTouchStart_);this.element_.removeEventListener("touchend",this.boundOnTouchEnd_);this.element_.removeEventListener("touchmove",this.boundOnTouchMove_);this.element_.removeEventListener("touchcancel",this.boundOnTouchCancel_);this.pass_.cancel()};T.prototype.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.overservers_[d];e||(this.recognizers_.push(c),e=new D,this.overservers_[d]=e);return e.add(b)};
T.prototype.onPointerDown=function(a){return this.pointerDownObservable_.add(a)};T.prototype.onTouchStart_=function(a){var b=E.timer.now();this.wasEventing_=!1;this.pointerDownObservable_.fire(a);for(var c=0;c<this.recognizers_.length;c++)this.ready_[c]||(this.pending_[c]&&this.pending_[c]<b&&this.stopTracking_(c),this.recognizers_[c].onTouchStart(a)&&this.startTracking_(c));this.afterEvent_(a)};
T.prototype.onTouchMove_=function(a){for(var b=E.timer.now(),c=0;c<this.recognizers_.length;c++)this.tracking_[c]&&(this.pending_[c]&&this.pending_[c]<b?this.stopTracking_(c):this.recognizers_[c].onTouchMove(a)||this.stopTracking_(c));this.afterEvent_(a)};
T.prototype.onTouchEnd_=function(a){for(var b=E.timer.now(),c=0;c<this.recognizers_.length;c++)this.tracking_[c]&&(this.pending_[c]&&this.pending_[c]<b?this.stopTracking_(c):(this.recognizers_[c].onTouchEnd(a),(!this.pending_[c]||this.pending_[c]<b)&&this.stopTracking_(c)));this.afterEvent_(a)};T.prototype.onTouchCancel_=function(a){for(var b=0;b<this.recognizers_.length;b++)this.cancelEventing_(b);this.afterEvent_(a)};
T.prototype.signalReady_=function(a,b){if(this.eventing_)a.acceptCancel();else{for(var c=E.timer.now(),d=0;d<this.recognizers_.length;d++)this.recognizers_[d]==a&&(this.ready_[d]=c+b,this.pending_[d]=0);this.passAfterEvent_=!0}};T.prototype.signalPending_=function(a,b){if(this.eventing_)a.acceptCancel();else for(var c=E.timer.now(),d=0;d<this.recognizers_.length;d++)this.recognizers_[d]==a&&(this.pending_[d]=c+b)};
T.prototype.signalEnd_=function(a){this.eventing_==a&&(this.eventing_=null,this.wasEventing_=!0)};T.prototype.signalEmit_=function(a,b,c){h.assert(this.eventing_==a,"Recognizer is not currently allowed: %s",a.getType());var d=this.overservers_[a.getType()];d&&d.fire(new xa(a.getType(),b,E.timer.now(),c))};
T.prototype.afterEvent_=function(a){var b=!!this.eventing_||this.wasEventing_;this.wasEventing_=!1;if(!b)for(var c=E.timer.now(),d=0;d<this.recognizers_.length;d++)if(this.ready_[d]||this.pending_[d]&&this.pending_[d]>=c){b=!0;break}b&&(a.stopPropagation(),a.preventDefault());this.passAfterEvent_&&(this.passAfterEvent_=!1,this.doPass_())};
T.prototype.doPass_=function(){for(var a=E.timer.now(),b=-1,c=0;c<this.recognizers_.length;c++)if(!this.ready_[c])this.pending_[c]&&this.pending_[c]<a&&this.stopTracking_(c);else if(-1==b||this.ready_[c]>this.ready_[b])b=c;if(-1!=b){for(var d=c=0;d<this.recognizers_.length;d++)!this.ready_[d]&&this.tracking_[d]&&(c=Math.max(c,this.pending_[d]-a));2>c?this.startEventing_(b):this.pass_.schedule(c)}};
T.prototype.startEventing_=function(a){for(var b=this.recognizers_[a],c=0;c<this.recognizers_.length;c++)c!=a&&this.cancelEventing_(c);this.ready_[a]=0;this.pending_[a]=0;this.eventing_=b;b.acceptStart()};T.prototype.startTracking_=function(a){this.tracking_[a]=!0;this.pending_[a]=0};T.prototype.stopTracking_=function(a){this.tracking_[a]=!1;this.pending_[a]=0;this.ready_[a]||this.recognizers_[a].acceptCancel()};T.prototype.cancelEventing_=function(a){this.ready_[a]=0;this.stopTracking_(a)};
function U(a,b){this.type_=a;this.manager_=b}U.prototype.getType=function(){return this.type_};U.prototype.signalReady=function(a){this.manager_.signalReady_(this,a)};U.prototype.signalPending=function(a){this.manager_.signalPending_(this,a)};U.prototype.signalEnd=function(){this.manager_.signalEnd_(this)};U.prototype.signalEmit=function(a,b){this.manager_.signalEmit_(this,a,b)};U.prototype.acceptStart=function(){};U.prototype.acceptCancel=function(){};U.prototype.onTouchStart=function(){return!1};
U.prototype.onTouchMove=function(){return!1};U.prototype.onTouchEnd=function(){};function V(a,b,c,d){U.call(this,a,b);this.horiz_=c;this.vert_=d;this.eventing_=!1;this.velocityY_=this.velocityX_=this.prevTime_=this.lastTime_=this.startTime_=this.prevY_=this.prevX_=this.lastY_=this.lastX_=this.startY_=this.startX_=0}g.inherits(V,U);V.prototype.onTouchStart=function(a){a=a.touches;if(!a||1!=a.length)return!1;this.startTime_=E.timer.now();this.startX_=a[0].clientX;this.startY_=a[0].clientY;return!0};
V.prototype.onTouchMove=function(a){var b=a.changedTouches||a.touches;if(b&&1==b.length){var c=b[0].clientX,b=b[0].clientY;this.lastX_=c;this.lastY_=b;if(this.eventing_)this.emit_(!1,!1,a);else if(a=Math.abs(c-this.startX_),c=Math.abs(b-this.startY_),this.horiz_&&this.vert_)(8<=a||8<=c)&&this.signalReady(-10);else if(this.horiz_)if(8<=a&&a>c)this.signalReady(-10);else{if(8<=c)return!1}else if(this.vert_)if(8<=c&&c>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1}return!0};
V.prototype.onTouchEnd=function(a){this.end_(a)};V.prototype.acceptStart=function(){this.eventing_=!0;this.prevX_=this.startX_;this.prevY_=this.startY_;this.prevTime_=this.startTime_;this.startX_=this.lastX_;this.startY_=this.lastY_;this.emit_(!0,!1,null)};V.prototype.acceptCancel=function(){this.eventing_=!1};
V.prototype.emit_=function(a,b,c){this.lastTime_=E.timer.now();var d=this.lastTime_-this.prevTime_;if(!b&&4<d||b&&16<d)this.velocityX_=J.calcVelocity(this.lastX_-this.prevX_,d,this.velocityX_),this.velocityY_=J.calcVelocity(this.lastY_-this.prevY_,d,this.velocityY_),this.velocityX_=1E-4<Math.abs(this.velocityX_)?this.velocityX_:0,this.velocityY_=1E-4<Math.abs(this.velocityY_)?this.velocityY_:0,this.prevX_=this.lastX_,this.prevY_=this.lastY_,this.prevTime_=this.lastTime_;this.signalEmit({first:a,last:b,
time:this.lastTime_,deltaX:this.horiz_?this.lastX_-this.startX_:0,deltaY:this.vert_?this.lastY_-this.startY_:0,velocityX:this.horiz_?this.velocityX_:0,velocityY:this.vert_?this.velocityY_:0},c)};V.prototype.end_=function(a){this.eventing_&&(this.eventing_=!1,this.emit_(!1,!0,a),this.signalEnd())};function W(a){V.call(this,"swipe-x",a,!0,!1)}g.inherits(W,V);function X(a){AMP.BaseElement.apply(this,arguments)}g.inherits(X,AMP.BaseElement);X.prototype.buildCallback=function(){this.buildCarousel();this.buildButtons();this.setupGestures();this.setControlsState();(this.showControls_=this.element.hasAttribute("controls"))&&this.element.classList.add("-amp-carousel-has-controls")};
X.prototype.buildButtons=function(){var a=this;this.prevButton_=document.createElement("div");this.prevButton_.classList.add("amp-carousel-button");this.prevButton_.classList.add("amp-carousel-button-prev");this.prevButton_.setAttribute("role","button");this.prevButton_.setAttribute("aria-label","previous");this.prevButton_.onclick=function(){a.prevButton_.classList.contains("amp-disabled")||a.go(-1,!0)};this.element.appendChild(this.prevButton_);this.nextButton_=document.createElement("div");this.nextButton_.classList.add("amp-carousel-button");
this.nextButton_.classList.add("amp-carousel-button-next");this.nextButton_.setAttribute("role","button");this.nextButton_.setAttribute("aria-label","next");this.nextButton_.onclick=function(){a.nextButton_.classList.contains("amp-disabled")||a.go(1,!0)};this.element.appendChild(this.nextButton_)};X.prototype.prerenderAllowed=function(){return!0};X.prototype.isRelayoutNeeded=function(){return!0};X.prototype.buildCarousel=function(){};X.prototype.setupGestures=function(){};
X.prototype.go=function(a,b){this.goCallback(a,b)};X.prototype.goCallback=function(){};X.prototype.setControlsState=function(){this.prevButton_.classList.toggle("amp-disabled",!this.hasPrev());this.prevButton_.setAttribute("aria-disabled",!this.hasPrev());this.nextButton_.classList.toggle("amp-disabled",!this.hasNext());this.nextButton_.setAttribute("aria-disabled",!this.hasNext())};
X.prototype.hintControls=function(){var a=this;!this.showControls_&&this.isInViewport()&&this.getVsync().mutate(function(){a.element.classList.add("-amp-carousel-button-start-hint");E.timer.delay(function(){a.deferMutate(function(){return a.element.classList.remove("-amp-carousel-button-start-hint")})},1E3)})};X.prototype.isReadyToBuild=function(){return!1};X.prototype.documentInactiveCallback=function(){return!0};X.prototype.hasPrev=function(){};X.prototype.hasNext=function(){};function Y(a){X.apply(this,arguments)}g.inherits(Y,X);Y.prototype.isLayoutSupported=function(a){return a==G.Layout.FIXED||a==G.Layout.FIXED_HEIGHT};
Y.prototype.buildCarousel=function(){var a=this;this.pos_=0;this.cells_=this.getRealChildren();this.container_=document.createElement("div");z.setStyles(this.container_,{whiteSpace:"nowrap",position:"absolute",zIndex:1,top:0,left:0,bottom:0});this.element.appendChild(this.container_);this.cells_.forEach(function(b){a.setAsOwner(b);b.style.display="inline-block";b!=a.cells_[0]&&(b.style.marginLeft="8px");a.container_.appendChild(b)})};
Y.prototype.layoutCallback=function(){this.doLayout_(this.pos_);this.preloadNext_(this.pos_,1);this.setControlsState();return Promise.resolve()};Y.prototype.viewportCallback=function(a){this.updateInViewport_(this.pos_,this.pos_);a&&this.hintControls()};
Y.prototype.goCallback=function(a,b){var c=this.nextPos_(this.pos_,a);if(c!=this.pos_){var d=this.pos_;this.pos_=c;if(b){var e=this;P.animate(R.setStyles(this.container_,{transform:R.translateX(R.numeric(-d,-c))}),200,"ease-out").thenAlways(function(){e.commitSwitch_(d,c)})}else this.commitSwitch_(d,c)}};Y.prototype.commitSwitch_=function(a,b){z.setStyles(this.container_,{transform:z.translateX(-b)});this.doLayout_(b);this.preloadNext_(b,Math.sign(b-a));this.updateInViewport_(b,a);this.setControlsState()};
Y.prototype.nextPos_=function(a,b){var c=this.element.offsetWidth,d=this.container_.scrollWidth,e=a+b*c;return 0>e?0:d>=c&&e>d-c?d-c:e};Y.prototype.withinWindow_=function(a,b){for(var c=this.getLayoutWidth(),d=0;d<this.cells_.length;d++){var e=this.cells_[d];e.offsetLeft+e.offsetWidth>=a&&e.offsetLeft<=a+c&&b(e)}};Y.prototype.doLayout_=function(a){var b=this;this.withinWindow_(a,function(a){b.scheduleLayout(a)})};
Y.prototype.preloadNext_=function(a,b){var c=this.nextPos_(a,b);if(c!=a){var d=this;this.withinWindow_(c,function(a){d.schedulePreload(a)})}};Y.prototype.updateInViewport_=function(a,b){var c=this,d=[];this.withinWindow_(a,function(a){d.push(a);c.updateInViewport(a,!0)});if(b!=a){var e=this;this.withinWindow_(b,function(a){-1==d.indexOf(a)&&(e.updateInViewport(a,!1),e.schedulePause(a))})}};
Y.prototype.setupGestures=function(){var a=this;this.extent_=this.maxPos_=this.minPos_=this.startPos_=0;this.motion_=null;var b=T.get(this.element);b.onGesture(W,function(b){if(b.data.first)a.onSwipeStart_(b.data);a.onSwipe_(b.data);if(b.data.last)a.onSwipeEnd_(b.data)});b.onPointerDown(function(){a.motion_&&(a.motion_.halt(),a.motion_=null)})};Y.prototype.onSwipeStart_=function(){this.updateBounds_();this.startPos_=this.pos_;this.motion_=null};
Y.prototype.onSwipe_=function(a){this.pos_=this.boundPos_(this.startPos_-a.deltaX,!0);z.setStyles(this.container_,{transform:z.translateX(-this.pos_)});.05>Math.abs(a.velocityX)&&this.commitSwitch_(this.startPos_,this.pos_)};
Y.prototype.onSwipeEnd_=function(a){var b=this,c=void 0;if(.1<Math.abs(a.velocityX)){var d=this;this.motion_=J.continueMotion(this.pos_,0,-a.velocityX,0,function(a){a=.5*(d.boundPos_(a,!0)+d.boundPos_(a,!1));if(1>=Math.abs(a-d.pos_))return!1;d.pos_=a;z.setStyles(d.container_,{transform:z.translateX(-d.pos_)});return!0});c=this.motion_.thenAlways()}else c=Promise.resolve();return c.then(function(){var a=b.boundPos_(b.pos_,!1);if(!(1>Math.abs(a-b.pos_))){var c=R.numeric(b.pos_,a);return P.animate(function(a){b.pos_=
c(a);z.setStyles(b.container_,{transform:z.translateX(-b.pos_)})},250,L.bezierCurve(.4,0,.2,1.4)).thenAlways()}}).then(function(){b.commitSwitch_(b.startPos_,b.pos_);b.startPos_=b.pos_;b.motion_=null})};Y.prototype.updateBounds_=function(){var a=this.element.offsetWidth,b=this.container_.scrollWidth;this.minPos_=0;this.maxPos_=Math.max(b-a,0);this.extent_=Math.min(.4*a,200)};Y.prototype.boundPos_=function(a,b){var c=b?this.extent_:0;return Math.min(this.maxPos_+c,Math.max(this.minPos_-c,a))};
Y.prototype.hasPrev=function(){return 0!=this.pos_};Y.prototype.hasNext=function(){var a=this.getLayoutWidth();return this.pos_!=Math.max(this.container_.scrollWidth-a,0)};function Z(a){X.apply(this,arguments)}g.inherits(Z,X);Z.prototype.isLayoutSupported=function(a){return G.isLayoutSizeDefined(a)};
Z.prototype.buildCarousel=function(){var a=this;this.isLooping_=this.element.hasAttribute("loop");this.isAutoplayRequested_=this.element.hasAttribute("autoplay");this.autoplayDelay_=5E3;this.slides_=this.getRealChildren();this.slides_.forEach(function(b,c){a.setAsOwner(b);b.style.display=0<c?"none":"block";a.applyFillContent(b)});this.currentIndex_=0;this.autoplayTimeoutId_=null;AMP.assert(1<=this.slides_.length,"amp-carousel with type=slides should have at least 1 slide.");this.setupAutoplay_()};
Z.prototype.layoutCallback=function(){var a=this.curSlide_();a&&(this.scheduleLayout(a),this.preloadNext_(1));return Promise.resolve()};Z.prototype.viewportCallback=function(a){var b=this.curSlide_();b&&(this.updateInViewport(b,a),this.tryAutoplay_(1,!0),a&&this.hintControls())};
Z.prototype.goCallback=function(a,b){var c=this.nextIndex_(a);if(0<=c&&c!=this.currentIndex_){var d=this.slides_[c],e=this.curSlide_();this.currentIndex_=c;this.prepareSlide_(d,a);if(b){var f=this;e.style.zIndex=0;P.animate(this.createTransition_(e,d,a),200,"ease-out").thenAlways(function(){f.commitSwitch_(e,d);f.preloadNext_(a)})}else this.commitSwitch_(e,d)}this.tryAutoplay_(1,!0)};
Z.prototype.setupAutoplay_=function(){if(this.isAutoplayRequested_){var a=Number(this.element.getAttribute("delay"));0<a&&(this.autoplayDelay_=Math.max(1E3,a));this.element.hasAttribute("loop")||(this.element.setAttribute("loop",""),this.isLooping_=!0)}};Z.prototype.tryAutoplay_=function(a,b){this.tryCancelAutoplayTimeout_();this.isAutoplayRequested_&&this.isInViewport()&&(this.autoplayTimeoutId_=E.timer.delay(this.go.bind(this,a,b),this.autoplayDelay_))};
Z.prototype.tryCancelAutoplayTimeout_=function(){null!==this.autoplayTimeoutId_&&(E.timer.cancel(this.autoplayTimeoutId_),this.autoplayTimeoutId_=null)};Z.prototype.prepareSlide_=function(a,b){z.setStyles(a,{transform:z.translateX(b*this.element.offsetWidth),zIndex:1,display:"block"});this.scheduleLayout(a)};
Z.prototype.createTransition_=function(a,b,c){return R.all([R.setStyles(b,{transform:R.translateX(R.numeric(c*this.element.offsetWidth,0)),opacity:R.numeric(.8,1)}),R.setStyles(a,{transform:R.scale(R.numeric(1,.98)),opacity:R.numeric(1,.4)})])};
Z.prototype.commitSwitch_=function(a,b){z.setStyles(a,{display:"none",zIndex:0,transform:"",opacity:1});z.setStyles(b,{display:"block",zIndex:0,transform:"",opacity:1});this.scheduleLayout(b);this.updateInViewport(a,!1);this.updateInViewport(b,!0);this.setControlsState();this.schedulePause(a)};Z.prototype.curSlide_=function(){return this.slides_[this.currentIndex_]};
Z.prototype.nextIndex_=function(a){a=this.currentIndex_+a;0>a?a=this.slides_.length+a:a>=this.slides_.length&&(a%=this.slides_.length);return a};Z.prototype.preloadNext_=function(a){a=this.nextIndex_(a);a!=this.currentIndex_&&this.schedulePreload(this.slides_[a])};Z.prototype.setupGestures=function(){var a=this;this.swipeState_=null;T.get(this.element).onGesture(W,function(b){if(b.data.first)a.onSwipeStart_(b.data);a.onSwipe_(b.data);if(b.data.last)a.onSwipeEnd_(b.data)})};
Z.prototype.onSwipeStart_=function(){var a=this.curSlide_(),b=this.element.offsetWidth,c=0,d=0,e=R.NOOP,f=R.NOOP,n=Z.getRelativeIndex(this.currentIndex_,-1,this.slides_.length),B=Z.getRelativeIndex(this.currentIndex_,1,this.slides_.length);if(this.isLooping_||0<=this.currentIndex_-1)c=this.slides_[n],this.prepareSlide_(c,-1),e=this.createTransition_(a,c,-1),c=-1;if(this.isLooping_||this.currentIndex_+1<this.slides_.length)d=this.slides_[B],this.prepareSlide_(d,1),f=this.createTransition_(a,d,1),d=
1;this.swipeState_={containerWidth:b,prevTr:e,nextTr:f,prevIndex:n,nextIndex:B,min:c,max:d,pos:0,currentIndex:this.currentIndex_}};Z.prototype.onSwipe_=function(a){var b=this.swipeState_;b&&b.currentIndex==this.currentIndex_&&(a=Math.min(b.max,Math.max(b.min,-a.deltaX/b.containerWidth)),b.nextTr(0<a?a:0),b.prevTr(0>a?-a:0),b.pos=a)};
Z.prototype.onSwipeEnd_=function(a){var b=this,c=this.swipeState_;if(c&&c.currentIndex==this.currentIndex_){this.swipeState_=null;var d=c.pos;0<=c.pos*-a.velocityX&&(d=c.pos-Math.sign(a.velocityX)*(.2<Math.abs(a.velocityX)?1:0));var d=Math.min(c.max,Math.max(c.min,d)),e=.55<=Math.abs(d)?Math.sign(d):0;a=void 0;if(e!=c.pos){var f=R.numeric(c.pos,e);a=P.animate(function(a){a=f(a);c.nextTr(0<a?a:0);c.prevTr(0>a?-a:0);c.pos=a},150,L.bezierCurve(.19,.49,.2,1)).thenAlways()}else a=Promise.resolve();return a.then(function(){if(c.currentIndex==
b.currentIndex_){var a=b.slides_[b.currentIndex_];.5<e?(c.nextTr(1),b.currentIndex_=c.nextIndex,b.commitSwitch_(a,b.slides_[b.currentIndex_])):-.5>e?(c.prevTr(1),b.currentIndex_=c.prevIndex,b.commitSwitch_(a,b.slides_[b.currentIndex_])):(c.nextTr(0),c.prevTr(0))}})}};Z.prototype.hasPrev=function(){return this.isLooping_?!0:0!=this.currentIndex_};Z.prototype.hasNext=function(){return this.isLooping_?!0:this.currentIndex_<this.slides_.length-1};Z.getRelativeIndex=function(a,b,c){return(a+b+c)%c};AMP.registerElement("amp-carousel",function(a){return a.hasAttribute("type")&&"slides"==a.getAttribute("type")?new Z(a):new Y(a)},'.amp-carousel-button{position:absolute;box-sizing:border-box;top:50%;height:34px;width:34px;border-radius:2px;opacity:0;pointer-events:all;background-color:rgba(0,0,0,.5);background-position:50% 50%;background-repeat:no-repeat;-webkit-transform:translateY(-50%);transform:translateY(-50%);visibility:hidden;z-index:10}.amp-mode-mouse .amp-carousel-button,amp-carousel[controls] .amp-carousel-button{opacity:1;visibility:visible}.amp-carousel-button-prev{left:16px;background-image:url(\'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="%23fff" viewBox="0 0 18 18"><path d="M15 8.25H5.87l4.19-4.19L9 3 3 9l6 6 1.06-1.06-4.19-4.19H15v-1.5z" /></svg>\');background-size:18px 18px}.amp-carousel-button-next{right:16px;background-image:url(\'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="%23fff" viewBox="0 0 18 18"><path d="M9 3L7.94 4.06l4.19 4.19H3v1.5h9.13l-4.19 4.19L9 15l6-6z" /></svg>\');background-size:18px 18px}:not(.amp-mode-mouse) .-amp-carousel-button-start-hint .amp-carousel-button:not(.amp-disabled){-webkit-animation:a 1s ease-in 0s 1 normal both;animation:a 1s ease-in 0s 1 normal both}@-webkit-keyframes a{0%{opacity:1;visibility:visible}to{opacity:0;visibility:hidden}}@keyframes a{0%{opacity:1;visibility:visible}to{opacity:0;visibility:hidden}}amp-carousel .amp-carousel-button.amp-disabled{-webkit-animation:none;animation:none;opacity:0;visibility:hidden}\n/*# sourceURL=/extensions/amp-carousel/0.1/amp-carousel.css*/');
});
//# sourceMappingURL=amp-carousel-0.1.js.map

