(window.AMP = window.AMP || []).push(function(AMP) {var process={env:{NODE_ENV:"production"}};var f={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};f.global=f.getGlobal(this);f.initSymbol=function(){f.global.Symbol||(f.global.Symbol=f.Symbol);f.initSymbol=function(){}};f.symbolCounter_=0;f.Symbol=function(a){return"jscomp_symbol_"+a+f.symbolCounter_++};f.initSymbolIterator=function(){f.initSymbol();f.global.Symbol.iterator||(f.global.Symbol.iterator=f.global.Symbol("iterator"));f.initSymbolIterator=function(){}};
f.makeIterator=function(a){f.initSymbolIterator();if(a[f.global.Symbol.iterator])return a[f.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};f.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};f.arrayFromIterable=function(a){return a instanceof Array?a:f.arrayFromIterator(f.makeIterator(a))};
f.arrayFromArguments=function(a){for(var b=[],d=0;d<a.length;d++)b.push(a[d]);return b};f.inherits=function(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(f.global.Object.defineProperties){var e=f.global.Object.getOwnPropertyDescriptor(b,c);void 0!==e&&f.global.Object.defineProperty(a,c,e)}else a[c]=b[c]};var h={};function k(a){return Error(a+"\u200b\u200b\u200b")}h.ASSERT_SENTINEL="\u200b\u200b\u200b";h.assert=function(a,b,d){var c=void 0;if(!a){var e=(b||"Assertion failed").split("%s"),g=e.shift(),p=g,w=[];""!=g&&w.push(g);for(g=2;g<arguments.length;g++){var m=arguments[g];m&&m.tagName&&(c=m);var B=e.shift();w.push(m);var C=B.trim();""!=C&&w.push(C);m=m instanceof Element?m.tagName.toLowerCase()+(m.id?"#"+m.id:""):m;p+=m+B}e=k(p);e.fromAssert=!0;e.associatedElement=c;e.messageArray=w;throw e;}return a};
h.assertEnumValue=function(a,b,d){for(var c in a)if(a[c]==b)return a[c];throw Error("Unknown "+(d||"enum")+' value: "'+b+'"');};h.userError=k;h.isAssertErrorMessage=function(a){return 0<=a.indexOf("\u200b\u200b\u200b")};var l={},n=Object.create(null),q="Webkit webkit Moz moz ms O o".split(" ");function r(a){return a.charAt(0).toUpperCase()+a.slice(1)}function t(a,b,d){var c=n[b];if(!c||d){c=b;if(void 0===a[b]){var e=r(b);a:{for(var g=0;g<q.length;g++){var p=q[g]+e;if(void 0!==a[p]){e=p;break a}}e=""}void 0!==a[e]&&(c=e)}d||(n[b]=c)}return c}function u(a,b,d,c,e){(b=t(a.style,b,e))&&(a.style[b]=c?d+c:d)}function v(a){return a+"px"}l.camelCaseToTitleCase=r;l.getVendorJsPropertyName=t;l.setStyle=u;
l.getStyle=function(a,b,d){return(b=t(a.style,b,d))?a.style[b]:void 0};l.setStyles=function(a,b){for(var d in b)u(a,d,b[d])};l.toggle=function(a,b){void 0===b&&(b="none"==a.style.display);a.style.display=b?"":"none"};l.px=v;l.translateX=function(a){return"string"==typeof a?"translateX("+a+")":"translateX("+v(a)+")"};l.translate=function(a,b){"number"==typeof a&&(a=v(a));if(void 0===b)return"translate("+a+")";"number"==typeof b&&(b=v(b));return"translate("+a+","+b+")"};
l.scale=function(a){return"scale("+a+")"};var x={};function y(a){this.win=a;this.resolved_=Promise.resolve();this.taskCount_=0;this.canceled_={};this.startTime_=this.now()}y.prototype.now=function(){return Number(new Date)};y.prototype.timeSinceStart=function(){return this.now()-this.startTime_};y.prototype.delay=function(a,b){if(!b){var d=this,c="p"+this.taskCount_++;this.resolved_.then(function(){d.canceled_[c]?delete d.canceled_[c]:a()});return c}return this.win.setTimeout(a,b)};
y.prototype.cancel=function(a){"string"==typeof a?this.canceled_[a]=!0:this.win.clearTimeout(a)};y.prototype.promise=function(a,b){var d=this,c=null;return(new Promise(function(e,g){c=d.delay(function(){c=-1;e(b)},a);-1==c&&g(Error("Failed to schedule timer."))})).catch(function(a){-1!=c&&d.cancel(c);throw a;})};
y.prototype.timeoutPromise=function(a,b,d){var c=this,e=null,g=(new Promise(function(b,g){e=c.delay(function(){e=-1;g(h.userError(d||"timeout"))},a);-1==e&&g(Error("Failed to schedule timer."))})).catch(function(a){-1!=e&&c.cancel(e);throw a;});return b?Promise.race([g,b]):g};var z=new y(window);x.Timer=y;x.timer=z;var A={},D={NODISPLAY:"nodisplay",FIXED:"fixed",FIXED_HEIGHT:"fixed-height",RESPONSIVE:"responsive",CONTAINER:"container",FILL:"fill"},E={"AMP-PIXEL":{width:"1px",height:"1px"},"AMP-ANALYTICS":{width:"1px",height:"1px"},"AMP-AUDIO":null},F={"AMP-ANIM":!0,"AMP-BRIGHTCOVE":!0,"AMP-EMBED":!0,"AMP-IFRAME":!0,"AMP-IMG":!0,"AMP-INSTAGRAM":!0,"AMP-LIST":!0,"AMP-PINTEREST":!0,"AMP-VIDEO":!0};function G(a){h.assert(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax)$/.test(a),"Invalid length value: %s",a);return a}
A.Layout=D;A.naturalDimensions_=E;A.LOADING_ELEMENTS_=F;A.parseLayout=function(a){for(var b in D)if(D[b]==a)return D[b]};A.getLayoutClass=function(a){return"-amp-layout-"+a};A.isLayoutSizeDefined=function(a){return a==D.FIXED||a==D.FIXED_HEIGHT||a==D.RESPONSIVE||a==D.FILL};A.isInternalElement=function(a){return(a="string"==typeof a?a:a.tagName)&&0==a.toLowerCase().indexOf("i-")};
A.parseLength=function(a){return"number"==typeof a?a+"px":a&&/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax)?$/.test(a)?/^\d+(\.\d+)?$/.test(a)?a+"px":a:void 0};A.assertLength=G;A.assertLengthOrPercent=function(a){h.assert(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|%)$/.test(a),"Invalid length or percent value: %s",a);return a};A.getLengthUnits=function(a){G(a);return h.assert(a.match(/[a-z]+/i),"Failed to read units from %s",a)[0]};A.getLengthNumeral=function(a){return parseFloat(a)};
A.hasNaturalDimensions=function(a){a=a.toUpperCase();return void 0!==E[a]};A.getNaturalDimensions=function(a){a=a.toUpperCase();h.assert(void 0!==E[a]);if(!E[a]){var b=a.replace(/^AMP\-/,""),b=document.createElement(b);b.controls=!0;b.style.position="absolute";b.style.visibility="hidden";document.body.appendChild(b);E[a]={width:(b.offsetWidth||1)+"px",height:(b.offsetHeight||1)+"px"};document.body.removeChild(b)}return E[a]};A.isLoadingAllowed=function(a){return F[a.toUpperCase()]||!1};var H={};function I(a,b,d,c){function e(a){d(a);p()}var g=c||!1,p=void 0,p=function(){a.removeEventListener(b,e,g)};a.addEventListener(b,e,g);return p}function J(a){return a.complete||"complete"==a.readyState}function K(a,b,d){var c=void 0,c=void 0===d?a:x.timer.timeoutPromise(d||0,a);return b?c.then(function(a){b();return a},function(a){b();throw a;}):c}H.listen=function(a,b,d,c){var e=c||!1;a.addEventListener(b,d,e);return function(){a.removeEventListener(b,d,e)}};H.listenOnce=I;
H.listenOncePromise=function(a,b,d,c){var e=void 0,g=new Promise(function(c){e=I(a,b,c,d)});return K(g,e,c)};H.isLoaded=J;H.loadPromise=function(a,b){var d=void 0,c=void 0,e=new Promise(function(b,e){J(a)?b(a):(d="AUDIO"===a.tagName||"VIDEO"===a.tagName?I(a,"loadstart",function(){return b(a)}):I(a,"load",function(){return b(a)}),c=I(a,"error",function(){try{h.assert(!1,"Failed HTTP request for %s.",a)}catch(b){e(b)}}))});return K(e,function(){d&&d();c&&c()},b)};function L(a){AMP.BaseElement.apply(this,arguments)}f.inherits(L,AMP.BaseElement);L.prototype.preconnectCallback=function(a){this.preconnect.url("../https@www.youtube.com/",a);this.preconnect.url("../https@s.ytimg.com/",a);this.preconnect.url("../https@i.ytimg.com/",a)};L.prototype.isLayoutSupported=function(a){return A.isLayoutSizeDefined(a)};
L.prototype.buildCallback=function(){var a=this.element.getAttribute("width"),b=this.element.getAttribute("height");this.width_=A.getLengthNumeral(a);this.height_=A.getLengthNumeral(b);this.playerState_=0;this.videoid_=AMP.assert(this.element.getAttribute("data-videoid")||this.element.getAttribute("video-id"),"The data-videoid attribute is required for <amp-youtube> %s",this.element);this.getPlaceholder()||this.buildImagePlaceholder_()};
L.prototype.layoutCallback=function(){var a=this,b=document.createElement("iframe");b.setAttribute("frameborder","0");b.setAttribute("allowfullscreen","true");b.src="../https@www.youtube.com/embed/"+encodeURIComponent(this.videoid_)+"@enablejsapi=1";this.applyFillContent(b);b.width=this.width_;b.height=this.height_;this.element.appendChild(b);this.iframe_=b;this.playerReadyPromise_=new Promise(function(b){a.playerReadyResolver_=b});this.getWin().addEventListener("message",function(b){return a.handleYoutubeMessages_(b)});
return H.loadPromise(b).then(function(){return x.timer.promise(300)}).then(function(){return a.listenToFrame_()}).then(function(){return a.playerReadyPromise_})};L.prototype.documentInactiveCallback=function(){this.iframe_&&this.iframe_.contentWindow&&1==this.playerState_&&this.pauseVideo_();return!1};L.prototype.pauseVideo_=function(){this.iframe_.contentWindow.postMessage(JSON.stringify({event:"command",func:"pauseVideo",args:""}),"*")};
L.prototype.handleYoutubeMessages_=function(a){if("../https@www.youtube.com/"==a.origin&&a.source==this.iframe_.contentWindow){var b=void 0;if(0==a.data.indexOf("{")){try{b=JSON.parse(a.data)}catch(d){return}"onReady"==b.event?this.playerReadyResolver_(this.iframe_):"infoDelivery"==b.event&&b.info&&void 0!==b.info.playerState&&(this.playerState_=b.info.playerState)}}};L.prototype.listenToFrame_=function(){this.iframe_.contentWindow.postMessage(JSON.stringify({event:"listening"}),"*")};
L.prototype.buildImagePlaceholder_=function(){var a=new Image,b=this.videoid_;l.setStyles(a,{"object-fit":"cover",visibility:"hidden"});a.src="../https@i.ytimg.com/vi/"+encodeURIComponent(this.videoid_)+"/sddefault.jpg";a.setAttribute("placeholder","");a.width=this.width_;a.height=this.height_;this.element.appendChild(a);this.applyFillContent(a);H.loadPromise(a).then(function(){if(120==a.naturalWidth&&90==a.naturalHeight)throw Error("sddefault.jpg is not found");}).catch(function(){a.src="../https@i.ytimg.com/vi/"+
encodeURIComponent(b)+"/hqdefault.jpg";return H.loadPromise(a)}).then(function(){l.setStyles(a,{visibility:""})})};AMP.registerElement("amp-youtube",L);
});
//# sourceMappingURL=amp-youtube-0.1.js.map

